name: deploiement-dockerhub-main

on:
  push:
    branches:
      - main 
      - connexion-docker 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push backend
        uses: docker/build-push-action@v3.1.1
        # voir : https://github.com/marketplace/actions/build-and-push-docker-images#customizing
        with:
          context: "{{defaultContext}}" # Répertoire de contexte (racine du repo par défaut)
          file: ./backend/Dockerfile  # Chemin vers le Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/backend:latest
      - 
        name: Build and push frontend
        uses: docker/build-push-action@v3.1.1
        with:
          context: "{{defaultContext}}"
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/image-frontend:latest